# Generated by Django 2.1.3 on 2018-11-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdDatetime',
            new_name='createDatetime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updatedDatetime',
            new_name='updateDatetime',
        ),
    ]
