# Generated by Django 2.1.3 on 2018-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20181122_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doneDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
