# Generated by Django 2.1.3 on 2018-11-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20181123_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completedDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
