# Generated by Django 2.1.3 on 2019-01-11 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_task_completeddatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskOwnerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
