# Generated by Django 2.1.5 on 2019-01-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_taskownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskOwnerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
